name: shift_app
description: Shift tracking app with Google integration
publish_to: 'none'
version: 0.5.29+0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  google_sign_in: ^6.3.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1
  http: ^0.13.6
  intl: ^0.19.0
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  background_fetch: ^1.3.8
  package_info_plus: ^4.1.0
  url_launcher: ^6.2.4
  yaml: ^3.1.1
  dio: ^5.4.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  generate: true